### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [Eblohm/project6#1]
I seem to be getting an `Internal Server Error` when I enter "uk" for the country field. Can you investigate?

**Comment by Eblohm** [comment]
UK isn't supported by the API for some reason, you have to us GB instead.

**Comment by chrisvfritz** [comment]
If there are only a few supported formats, I'd suggest a `<select>` tag here instead, to avoid bad data. Can you update?

**Comment by Eblohm** [comment]
Just pushed the update! Only 4 countries are supported by the API, so I added all 4. 

Also, I changed my settings to fix the indentation issue according to your cheatsheet, I un-indented everything and just tried to re-indent it, but the spacing is still with a hard tab, and I'm not sure why.

**Comment by chrisvfritz** [comment]
:+1: Looks great!

## Points of improvement for future projects

### Ruby indentation

The standard indentation for Ruby (`.rb`) files is actually with two-space soft-tabs rather than hard-tabs. See if you can update your text editor to use two-space soft-tabs for all Ruby files. If you have trouble figuring it out, [this page may be helpful](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md). If it's not, just let me know and I'll be happy to point you in the right direction.
